Added support for detection of tercetos encadenados
linhd-postdata/rantanplan pull request #85
Opened 2020-06-15 13:17 UTC by alvp

2020-06-15 13:48 UTC, versae requested changes

2020-06-15 13:48 UTC, versae commented on src/rantanplan/rhymes.py
> +            structure_check = structure_re.fullmatch(rhyme)
The docstring needs to be updated.
```
consonance, a rhyme pattern (regex or callable), and a condition on the lengths of sylalbles
``

2020-06-15 13:48 UTC, versae commented on src/rantanplan/structures.py
> +    return output
The one liner ICYMI:
```
from collections import defaultdict
counter = defaultdict(int)                                                                                                                   
return "".join([str(counter.update({c: counter[c] + 1}) or counter[c] - 1) for c in s])
```
I would make this function return the plain list of numbers.

Not sure the function name is descriptive enough.

2020-06-15 14:27 UTC, alvp commented on src/rantanplan/rhymes.py
> +            structure_check = structure_re.fullmatch(rhyme)
True, done

2020-06-15 17:25 UTC, versae commented on src/rantanplan/structures.py
> +        output.append(str(count))
Any reason why this function needs to return the counts as strings? I know it's used in the main function, but maybe it'd be better to return numbers and have the main function do what it needs with the counts?

2020-06-15 17:27 UTC, versae commented on src/rantanplan/structures.py
> +def rank_character_occurrences(string):
Aha! What about `get_rhyme_pattern_counts()`?

2020-06-16 09:02 UTC, versae approved these changes

2020-06-16 09:02 UTC, merged